services:
  caddy:
    image: caddy:2.10.2
    restart: unless-stopped
    volumes:
      # Caddy config
      - ./config/caddy/:/etc/caddy/:ro
      - ./data/caddy/data/:/data
      - ./data/caddy/config/:/config
    develop:
      watch:
        # NOTE: this is only for restarting the container when config changed
        # docker doesn't allow using mounted volumes in the path
        - action: sync+restart
          initial_sync: true
          path: ./config/
          target: /tmp/
    environment:
      FRONTEND_ALLOW_ORIGINS: ${FRONTEND_ALLOW_ORIGINS:-http://localhost:3000}
